name: Auto Release that generates binary, and upload new layer version to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-region: [ 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2', 'eu-central-1', 'eu-west-1', 'eu-north-1', 'ap-southeast-2', 'ca-central-1', 'sa-east-1', 'ap-northeast-1', 'ap-southeast-1', 'ap-south-1', 'ap-northeast-3', 'ap-northeast-2', 'eu-west-2', 'eu-west-3' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # AMD Build
      - name: Build AMD ZIP File
        working-directory: ./logzio-lambda-extensions-logs
        runs: ./build-zip.sh
      - name: Upload to AWS region ${{ matrix.aws-region }}
        working-directory: ./logzio-lambda-extensions-logs
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.3
        with:
          zip-file: './bin/extension.zip'
          lambda-name: 'LogzioLambdaExtensionLogs'
          AWS_REGION: ${{ matrix.aws-region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # ARM Build
      - name: Build ARM ZIP File
        working-directory: ./logzio-lambda-extensions-logs
        runs: ./build-arm-zip.sh
      - name: Upload to AWS region ${{ matrix.aws-region }}
        working-directory: ./logzio-lambda-extensions-logs
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.3
        with:
          zip-file: './bin/extension.zip'
          lambda-name: 'LogzioLambdaExtensionLogsArm'
          AWS_REGION: ${{ matrix.aws-region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
